# Generated by Django 4.1.3 on 2022-12-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1988-12-28'),
            preserve_default=False,
        ),
    ]
